### PR TITLE
Patch for #111 refine multiple resource event dragging 

### PR DESCRIPTION
**Pull request by yoh**
Hi @arshaw !

Please consider this patch for https://github.com/fullcalendar/fullcalendar-scheduler/issues/111

We can now : 
- move event with several resourceIds 
- resize event with several resourceIds
- merge resourceIds into on unique resourceId

It's not perfect but you can test it on ~~http://jsbin.com/kolopimoxa/1/edit?html,output~~
http://jsbin.com/gaqoginezu/1/edit?html,console,output (updated on 31/01/2017)
(bases on #111 toxaq example)

PS : I'm not very at ease with Coffeescript ;)

### CODE REVIEW

**Comment by yoh** [comment]
Build failed because I think this test is not correct :(

```
PhantomJS 2.1.1 (Linux 0.0.0) timeline-view event drag-n-drop restores multiple resources correctly with revert FAILED
	Expected '' to be 'c'.
	tests/timeline-event-dnd.coffee:81:35 <- tests/timeline-event-dnd.js:125:40
	Expected [ 'b', 'c' ] to be null.
	tests/timeline-event-dnd.coffee:82:36 <- tests/timeline-event-dnd.js:126:41
```

If we drag/drop an event with resourceIds `[a,b]` with `a -> c`, we want to have `[b,c]`, not `resourceId == 'a' && resourceIds == null` ?

I can update this PR with this patch for test if you want : 

````
diff --git a/tests/timeline-event-dnd.coffee b/tests/timeline-event-dnd.coffee
index c5fcdb8..2daf4a2 100644
--- a/tests/timeline-event-dnd.coffee
+++ b/tests/timeline-event-dnd.coffee
@@ -78,8 +78,8 @@ describe 'timeline-view event drag-n-drop', ->
                                setTimeout -> # let the drop rerender
                                        expect(event.start).toEqualMoment('2015-11-29T05:00:00')
                                        expect(event.end).toEqualMoment('2015-11-29T06:00:00')
-                                       expect(event.resourceId).toBe('c')
-                                       expect(event.resourceIds).toBe(null)
+                                       # expect(event.resourceId).toBe(null) # event.resourceId is ''
+                                       expect(event.resourceIds).toEqual([ 'b', 'c' ])
                                        revert()
                                        expect(event.start).toEqualMoment('2015-11-29T02:00:00')
                                        expect(event.end).toEqualMoment('2015-11-29T03:00:00')
````

**Comment by micbenner** [comment]
Good stuff mate, world love to see this merged.

**Comment by arshaw** [comment]
Thanks! I'll take a look at this and consider merging it after I get the current release out, which I am actively working on.

**Comment by jasonlewis** [comment]
Any idea when this patch will make it into a release?

**Comment by yoh** [comment]
I update my fork with your current master (by merge).

Updated example is here http://jsbin.com/gaqoginezu/1/edit?html,console,output
(based on fullcalendar-3.1.0 and fullcalendar-scheduler current master)

**Comment by arshaw** [comment]
thanks. i've created an alternative implementation of this and merged it into the `next-release` branch:
https://github.com/fullcalendar/fullcalendar-scheduler/commits/next-release

Please follow #111 for future updates. should be released very soon.

**Pull request closed without merging**
