### PR TITLE
Adding license options

### PR DESCRIPTION
**Pull request by marclaporte**
Info taken from https://fullcalendar.io/scheduler/license/

### CODE REVIEW

**Comment by arshaw** [comment]
thank @marclaporte . This "Commercial or CC BY-NC-ND 4.0 or GPLv3" string, where you're basically just "or"-ing license names together... is there a precedent for that? Have you seen other projects do it?

also, could you sign this CLA? http://goo.gl/forms/C0M1MMHPaxUcXlv33

**Comment by marclaporte** [comment]
Good point. What I did is not quite right: https://getcomposer.org/doc/04-schema.md#license

**Comment by marclaporte** [comment]
I signed the CLA. I don't know why Travis CI build would fail because of this trivial commit.

Thanks!

**Comment by marclaporte** [comment]
Can you force it?  Thanks!

**Comment by arshaw** [comment]
we'll use #466 instead. closing...

**Pull request closed without merging**
