### PR TITLE
Improve performance for rendering scrollFollowerSprites

### PR DESCRIPTION
**Pull request by MartijnWelker**
Mentioned in #277

### CODE REVIEW

**Comment by MartijnWelker** [comment]
@arshaw Any comments on this ?

**Comment by arshaw** [comment]
Hey @MartijnWelker this looks good and pretty straightforward.

Would you mind signing this Contributor License Agreement?
http://goo.gl/forms/C0M1MMHPaxUcXlv33

Thanks!

**Comment by MartijnWelker** [comment]
@arshaw Signed, no problem !

**Comment by arshaw** [comment]
thanks! i will merge this for the next release

**Comment by arshaw** [comment]
queued for release
https://github.com/fullcalendar/fullcalendar-scheduler/commits/master
(i made some fixes)

**Comment by arshaw** [comment]
Released in [v1.8.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.8.0)

**Pull request closed without merging**
